# Generated by Django 6.0.6 on 2026-07-05 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Kategori')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('author', models.CharField(default='Admin', max_length=100, verbose_name='Penulis')),
                ('cover_url', models.URLField(blank=True, help_text='Tempel link gambar sampul anime (tidak perlu upload file).', verbose_name='URL Gambar Sampul')),
                ('excerpt', models.TextField(blank=True, help_text='Ringkasan singkat yang tampil di halaman depan.', max_length=300, verbose_name='Ringkasan')),
                ('content', models.TextField(verbose_name='Isi Artikel')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Skor anime versi penulis, contoh: 8.7', max_digits=3, null=True, verbose_name='Rating Anime (0-10)')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Jumlah Dilihat')),
                ('is_published', models.BooleanField(default=True, help_text='Hilangkan centang untuk menyimpan sebagai draf.', verbose_name='Terbitkan?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Postingan',
                'verbose_name_plural': 'Postingan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('body', models.TextField(verbose_name='Komentar')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Disetujui?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dikirim')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'verbose_name': 'Komentar',
                'verbose_name_plural': 'Komentar',
                'ordering': ['created_at'],
            },
        ),
    ]
