# Generated by Django 6.0.6 on 2026-07-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_url',
            field=models.CharField(blank=True, help_text='Link internet (https://...) atau path lokal (/static/img/anime/nama.jpg).', max_length=300, verbose_name='Gambar Sampul'),
        ),
    ]
